FROM python:3.9.1-alpine3.12

MAINTAINER Gyeongmin Ha "gaonrudal@gmail.com"

WORKDIR /flask/

COPY ./flask/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

ENV FLASK_APP=hello.py
ENTRYPOINT ["sh", "-c", "flask run --host=0.0.0.0 --port=80"]