FROM nginx:1.19.5-alpine

MAINTAINER Gyeongmin Ha "gaonrudal@gmail.com"

# RUN chown -R www-data:www-data /var/lib/nginx

WORKDIR /etc/nginx

COPY nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]
